server:
  context-path: /server
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8880
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
#  cache:
#    type: ehcache
#    ehcache:
#      config: config/ehcache.xml
  cache:
      type: redis

  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
 # mapper-locations: mybatis/**/*Mapper.xml
  #typeAliasesPackage: com.bootdo.**.domain
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#  notEmpty: true

domain: http://peake.mynatapp.cc/
#pay config
alipay:
  sandbox: false
  appid: 2
  private_key: MkGfbo94tfkBww99DvCRYhw+519SaSwhUCRqdr5JFMI/D0HAvnA1vtS+L7SHGD1par3ngd5UDJvCKTn2AEpHymTYoJuhfZ8pIfO3KPM3aAD4tq6H3GRnpjvRvpon/+mxnDNAgMBAAECggEAav+f55l1TjgpsPJ4hu/09htdgTtCf4/cdOQR25DSSaaJRlVCvLErM29KksvqM8xd24py1bm8VD9RPIRTKoMZWWPbubAVG4bL7T6P4okU6h3m4ZDZaJoJCspR037R0O0Rbs5jU5BqwGGOa4oYWe8pa0xms9kTeblXH8ig88S2B4qvGxceQzwpDnwEw6JeLiNfRmeBYStzfM6FracUC5EUqbLo04b/Jf4ZEZkS942ZUJ37gx2ULZZyj6R0GHwaC+J+pAYMGAT8Vwz+8jKcnjx4xP6jBsKLRWQRbhdsnjLsoPSU12TSM3wLW+2jz7AB9ym3JmYx+53/UHStWjTaProVpQKBgQC+MO0ZHy7n0NTZSQPCY3Afc8mL59030+ipePA+/2fi+1VLDKhsuZ20swgo4+0EdFdzs1aF/KlEQxmTMacFBbtxiKVoMxcyxBpELsq29VCuDsxowhQwPnzZSo+PMnZ7Qs2uHdQUQJM87zepfMajqbGIbT4HzeXuwukkXnb2ueBykwKBgQC0dnVWpDdZMryu04MqkEJiOh3Cke7AkjbZE3nbB8krwAIHwxE8dVpTHscHsVegGuSfuQTbOvSwC1s6xRNTP/ysvlQ/rqAg6hjYvqH+kzjanux4ruBpYwRfp4SqERd9WGbe1rCc9eIf2H+W7CEPeXmvnA2dMAr6EeCTVlVRkArLHwKBgAuqjKCh3QqzMJszc1uVJeeH/rDqRBOMmBTtKi9zEzhFGnJEEIC60gWnhbScZomDaWnbck89tFRPmV4CCbCxLVJFg3/kwmOGy+WqyRx3578FgVxbq0laS+Y4QJ4UBliBPISVp9CmNWHjepKW6MhZPF6V9NwdsSD4K7zjXoC73hypAoGAFXeR9cCLJP04HMPkcoe+ndiz+ZVKhXXfOGtsr3V5pM6ubyXxQvPizsh2fJ/IAK+ySp3DyiB1QwvWymLvLZQLBrGNbBXlzoSKeB4VPydcOAV3s9N5to+k0Ywn5+MonCyL8C4xzDojsA4c/2MPe7vDkfRKWkyAwcampGA8vfsYjZkCgYApaq4leggqSkXam5tkhBKzaKSny1BlpYjaLvot0ZfuBEOEpnQZJDcmxjZRGQegjskQeohK/GD883jkre2LpkHhlOehIoe+WoE4pS4kmi3g6dyj+dm0IQNk+2tdjFOWqFh6B8Zcfq9bmlVxiSEP4O8e4/k2uYxdoU4vJIqWCuGKxw==
  public_key: MIIK3ozmli6z/2Q9FqKBG0YGkYdGcW+Q1WpwLB2Zi7pKh4cE0LTSHInVHp1x7dwXnLrOFgi2KOqo4QonRdEsdsN7U2Julf6rXS30yxoAN3A+HkxXC1MTX+7keLsHZHgk9JvFNENHUs+XqvvaocCp6oW7GJGMnUOc21rnX+24y+2Y6I95sTh9ulX8Du1VvVMvtQoGBLzHsZ2sN9t1RbkU1ZQIDAQAB

